language: java
jdk:
  - openjdk17 # Використовуємо OpenJDK 17

# Завантаження та установка Terraform
before_install:
  - curl -o terraform.zip https://releases.hashicorp.com/terraform/1.3.0/terraform_1.3.0_linux_amd64.zip
  - unzip terraform.zip
  - sudo mv terraform /usr/local/bin/
  - terraform -version # Перевірка версії Terraform

# Встановлення залежностей
install: true

# Запуск тестів
script:
  - mvn clean test # Запускаємо тести
  - echo "Tests completed with exit code $?" >> results.log

# Додаткові кроки для Terraform
after_success:
  - export GOOGLE_CREDENTIALS=$(cat ./my-project-436711-060922fb417d.json) # Встановлюємо змінну середовища
  - terraform init # Ініціалізація Terraform
  - terraform validate # Перевірка конфігурацій
  - terraform plan # Генерація плану
  - terraform apply -auto-approve # Застосування плану

# Виконати деструкцію після завершення
after_failure:
  - terraform init # Оновлення блокування залежностей
  - terraform destroy -auto-approve # Знищення ресурсів у разі помилки
