language: java
jdk:
  - openjdk17

before_install:
  - curl -o terraform.zip https://releases.hashicorp.com/terraform/1.3.0/terraform_1.3.0_linux_amd64.zip
  - unzip terraform.zip
  - sudo mv terraform /usr/local/bin/
  - terraform -version

install: true

script:
  - mvn clean test
  - echo "Tests completed with exit code $?" >> results.log

after_success:
  - export GOOGLE_CREDENTIALS=$(cat ./my-project-436711-060922fb417d.json) # Встановлюємо змінну середовища
  - terraform init
  - terraform validate
  - terraform plan
  - terraform apply -auto-approve
  - terraform destroy -auto-approve # Деструкція ресурсів
